import { Inter } from "next/font/google";
import Layout from "./components/Layout";
import Head from "next/head";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "ООО «ДЕССЕД-Д»",
  description: "Generated by create next app",
  icons: [
    {
      rel: 'icon',
      type: 'image/x-icon',
      sizes: 'any',
      url: '/static/favicon.ico',
    },
  ],
};

export default function RootLayout({ children }) {
  
  return (
    <StoreProvider>
      <html lang="en">
        <body classNameName={inter.classNameName}>
          <Head>
            <title>My page title</title>
          </Head>
          <Layout>
            {children}
          </Layout>
        </body>
      </html>
    </StoreProvider>
  );
}
