import './Contacts.css';
export const metadata = {
    title: "Контакты | ООО «ДЕССЕД-Д»",
    description: "Generated by create next app",
    icons: [
      {
        rel: 'icon',
        type: 'image/x-icon',
        sizes: 'any',
        url: '/static/favicon.ico',
      },
    ],
  };

function Contacts() {
    return (
        <div className="wrapper">
            <div className="contacts">
                <div className="contacts__content">
                    <div className="contacts__content__left">
                        <span>ООО &laquo;ДЕССЕД-Д&raquo;</span>
                        <div className="contacts__content__left__number-mail">
                            <div className="contacts__content__left__number-mail__number">
                                <span>&#9990;</span>
                                <span>Телефон:</span>
                                <a href="tel:+79278175535" className="contacts__link">+7 (927) 817-55-35</a>
                            </div>
                            <div className="contacts__content__left__number-mail__mail">
                                <span>&#9993;</span>
                                <span>E-mail:</span>
                                <a href="mailto:dessed.d@yandex.ru" className="contacts__link">dessed.d@yandex.ru</a>
                            </div>
                        </div>
                        <div className="contacts__content__left__production">
                            <svg xmlns="http://www.w3.org/2000/svg" width="23" height="28" fill="currentColor" className="bi bi-geo-alt" viewBox="0 0 16 16">
                                <path d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A31.493 31.493 0 0 1 8 14.58a31.481 31.481 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94zM8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10z"/>
                                <path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                            </svg>
                            <span>Адрес производства:</span>
                            <a href="" className="contacts__link">Ульяновская обл., г. Димитровград, пр. Автостроителей, 78/71</a>
                        </div>
                    </div>
                    <div className="contacts__content__right">
                        <iframe src="https://yandex.ru/map-widget/v1/?lang=ru_RU&amp;scroll=true&amp;source=constructor-api&amp;um=constructor%3A2515d7929e0ec3ac90aeac5485f6be28f5ff5133135c06d5d084c4d5179e6dfa" frameborder="0" allowfullscreen="true" width="100%" height="430px" style={{display: 'block'}}></iframe>
                    </div>
                </div>
            </div>
            <div className="contacts__info">
                <span>Если вы ищете надёжного партнёра в области металлообработки, то обращайтесь к нам!</span>
                <ul>
                    <li>Мы готовы решить любые ваши задачи. В нашем распоряжении — парк разнообразного оборудования, которое позволяет обрабатывать металл под любые нужды.</li>
                    <li>Мы производим продукцию по эскизу, чертежу или техническому заданию, что даёт возможность получить детали, точно соответствующие вашим требованиям.</li>
                    <li>Мы гарантируем высокое качество продукции, потому что осуществляем 100% контроль собственным ОТК.</li>
                </ul>
                <span className="contacts__info__last-offer">Свяжитесь с нами прямо сейчас, чтобы начать сотрудничество!</span>
            </div>
        </div>
    );
}

export default Contacts;