import './About.css';
export const metadata = {
    title: "О нас | ООО «ДЕССЕД-Д»",
    description: "Generated by create next app",
    icons: [
      {
        rel: 'icon',
        type: 'image/x-icon',
        sizes: 'any',
        url: '/static/favicon.ico',
      },
    ],
  };

function About() {
    return (
        <div className="wrapper">
            <div className="content">
                <div className="content__info">
                    <span>Наше производство располагает развитой технической базой на основе оборудования ведущих мировых производителей, позволяющего изготовить технологическую оснастку, как собственной разработки, так и по чертежам заказчика. Производственный цикл по изготовлению пресс-форм и другой технологической оснастки производится на современных станках с ЧПУ.</span>
                    <span>Инструментальное производство осуществляет изготовление следующей технологической оснастки:</span> 
                </div>
                <div className="content__kinds">
                    <div className="content__kinds-item">
                        <div className="kind-one"></div>
                        <div>
                            <span className="title-kind-list">Штампы холодной листовой штамповки:</span>
                            <ul className="kind-list"> 
                                <li>вырубные;</li>
                                <li>формовочные;</li> 
                                <li>совмещенного действия;</li> 
                                <li>последовательного действия.</li>
                            </ul>
                        </div>
                    </div>
                    <div className="content__kinds-item">
                        <div className="kind-two"></div>
                        <div>
                            <span className="title-kind-list">Формы:</span>
                            <ul className="kind-list">
                                <li>пресс-формы для литья термопластичных материалов, в том числе и горячеканальные;</li> 
                                <li>пресс-формы для прямого прессования;</li> 
                                <li>вакуум-формы;</li> 
                                <li>литейные формы для литья.</li>
                            </ul>
                        </div>
                    </div>
                    <div className="content__kinds-item">
                        <div className="kind-three"></div>
                        <div>
                            <span className="title-kind-list">Приспособления:</span>
                            <ul className="kind-list"> 
                                <li>для сварки;</li> 
                                <li>для механической обработки;</li> 
                                <li>станочные приспособления;</li> 
                                <li>для разметки;</li> 
                                <li>приспособления специального назначения.</li>
                            </ul>
                        </div>
                    </div>
                    <div className="content__kinds-item">
                        <div className="kind-four"></div>
                        <div>
                            <span className="title-kind-list">Виды обработки:</span>
                            <ul className="kind-list"> 
                                <li>фрезерную обработку деталей на универсальных станках и обрабатывающих центрах;</li>
                                <li>шлифовальные работы;</li> 
                                <li>электроэрозионную обработку;</li> 
                                <li>заточку режущего инструмента;</li> 
                                <li>порезку заготовок на ленточно-пильных станках;</li> 
                                <li>термообработку конструкционных и инструментальных сталей.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default About;